namespace Challenge3
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Random rnd = new Random();

            //Generates random number between 5 and 50, used for the for loop statement.
            int randomNumberForLoop = rnd.Next(5, 50);

            string consoleMessage = "Calculating the sum = ";
            int answerOfForLoopNumbers = 0;

            //Loops through each iteration, max is generated by a random number between 5 and 50. 
            for (int i = 0; i < randomNumberForLoop; i++) {

                //Generation random number between 101 and 10.000
                int randomGeneratedNumber = rnd.Next(101, 10000);

                //Put the generated number inside the equation (printed to the console)
                consoleMessage += randomGeneratedNumber;

                //Adding the generated number to the equation for the answer.
                answerOfForLoopNumbers += randomGeneratedNumber;
                
                //Check if this is the last iteration, if so; then ignore the '+' operator.
                if (randomNumberForLoop - 1 != i)
                {
                    consoleMessage += " + ";
                }
            }

            Console.WriteLine(consoleMessage);
            Console.WriteLine($"The Result = {answerOfForLoopNumbers}");

            Console.ReadKey();
        }
    }
}
